In [175]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [152]:
data= pd.read_csv("C:/Users/Lenovo/Downloads/data1.csv", header=None)

In [153]:
npdata=np.asarray(data)
print(npdata.shape)

(20000, 20)


In [154]:
print(npdata.ndim)
print(npdata.shape)
print(npdata.size)

2
(20000, 20)
400000


In [155]:
label= pd.read_csv("C:/Users/Lenovo/Downloads/label1.csv", header=None)

In [156]:
nplabel=np.asarray(label)
print('size', nplabel.size)
print('ndim', nplabel.ndim)
print('shape', nplabel.shape)

size 20000
ndim 2
shape (20000, 1)


In [157]:
print(nplabel)

[[3]
 [2]
 [2]
 ...
 [2]
 [2]
 [0]]


In [158]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(nplabel)

c:\users\lenovo\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [159]:
maxValue=max(nplabel)
print(maxValue)

[4]


In [160]:
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(nplabel)
print(onehot_encoded.shape)

(20000, 5)


In [161]:
from sklearn.model_selection import train_test_split
trainData, testDataDash=train_test_split(npdata,train_size=0.8, test_size=0.2, shuffle= False)
trainlabelData, testLabelDash=train_test_split(onehot_encoded,train_size=0.8, test_size=0.2, shuffle= False)

In [162]:
print(testLabelDash)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [163]:
print(testDataDash.shape)
print(trainData.shape)
print(trainlabelData.shape)

(4000, 20)
(16000, 20)
(16000, 5)


In [164]:
print(trainData.shape)

(16000, 20)


In [165]:
validateData, testData=train_test_split(testDataDash,train_size=0.5, test_size=0.5, shuffle= False)
validateLabel, testLabel=train_test_split(testLabelDash,train_size=0.5, test_size=0.5, shuffle= False)
print(validateData.shape)

(2000, 20)


In [166]:
def act(func, val):
    if func== 1:
        return val * (val>0)
    elif func==3:
        return np.tanh(val)
    elif func==2:
        e_x = np.exp(val)
        return e_x / np.sum(e_x,axis=0, keepdims=True)
        


In [167]:
h=int(input())
b1 = np.zeros(h)
b2 = np.zeros(5)
print(b2.shape)

10
(5,)


In [168]:
std1 = (1/np.sqrt(20))
std2= (1/np.sqrt(h))
w1= np.random.normal(0, std1, (20,h))
w2= np.random.normal(0, std2, (h,5))


In [169]:
def frwdpass(data):
    a0=data
    z1=np.dot(a0,w1)+b1
    a1=act(3, z1)
    z2=np.dot(a1,w2)+b2
    a2=act(2, z2)
    return a0,a1,a2,z1,z2

In [170]:
alpha=0.0001

In [171]:
epochs=10

In [172]:
def costfunc(y,t):
    return -(t*(np.log(y))+(1-t)*np.log(1-y))

In [173]:
def accuracyfunc(output, labeldata, datasize):
    maxInRow=np.argmax(output, axis=1)
    maxInLabels= np.argmax(labeldata, axis=1)
    huehue=np.equal(maxInRow,maxInLabels)
    count=np.sum(huehue)
    return (count/datasize)*100

In [174]:
for j in range(epochs):
    for i in range (16):
        a0,a1,a2,z1,z2=frwdpass(trainData[(i*1000):(i+1)*1000,:])
        labelBatch=trainlabelData[(i*1000):(i+1)*1000,:]
        y=a2
        Del2=(a2-labelBatch)
        Del1=np.dot( Del2,w2.T)* (1-a1*a1)
        dcdw1=np.dot(a0.T, Del1)
        dcdw2=np.dot(a1.T, Del2)
        dcdb1=np.sum(Del1, axis=0)
        dcdb2=np.sum(Del2, axis=0)
        #updation of weights
        w1=w1-alpha*(dcdw1)
        w2=w2-alpha*(dcdw2)
        b1=b1-alpha*(dcdb1)
        b2=b2-alpha*(dcdb2)
    a0,a1,a2,z1,z2=frwdpass(trainData)
    ytrue=a2
    cost=np.sum(costfunc(ytrue, trainlabelData))/16000
    print(cost)
    accuracy=accuracyfunc(ytrue, trainlabelData, 16000)
    print(accuracy)

9.454488902898078
41.78125
9.250402239155056
59.11875
9.190561725443462
65.60000000000001
9.215792109273501
68.3125
9.298237538900393
70.19375
9.417654094203368
71.4375
9.553813567827826
72.24374999999999
9.705336081600489
72.96875
9.885844628282586
73.19375000000001
10.092799072997519
73.49375
